#!/bin/sh

prefix=/usr/local
SHARE=$prefix/share/house

HAPP=housenote

case $1 in
    remove)
        systemctl daemon-reload
        ;;
    purge)
        systemctl daemon-reload
        rm -f /etc/default/$HAPP
        rm -f /var/lib/house/note
        ;;
esac

